### ISSUE TITLE
No download for ADO Services?

### ISSUE THREAD

**Issue by klc126** [konradsikorski/VSS.Extension.ChangeState#17]
Hi I am looking to download and install this extension into my ADO organization - when I click the Install button, it redirects to my on prem TFS instance and not the ADO org.  I am browsing the marketplace from my ADO org, not the on prem TFS instance.

Does this not work with ADO? If it does, am I missing something? I really want to try this extension, it looks super helpful!

**Comment by konradsikorski** [comment]
Sorry to hear that. Unfortunately I cannot help you, the installation process is out of my control. You can check this article https://docs.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser
