### ISSUE TITLE
Cannot change reason for this item.

### ISSUE THREAD

**Issue by kglu** [konradsikorski/VSS.Extension.ChangeState#3]
Does not work (Win10 + TFS 15.112.26307.0).
statesLogic.js returns result "Cannot change reason for this item."
I noted there is a definition of  [var template = "Agile";] inside "changeStatus" function though i use Scrum. 
When i fix it on Scrum - seems it works! 
Please, check it

**Comment by konradsikorski** [comment]
Sorry you have to wait so long.
At the first time when you try use this extension did you have option to select project template? like here: https://github.com/konradsikorski/VSS.Extension.ChangeState#project-template-selection
If yes did you select Agile or Scrum? :)

**Comment by kglu** [comment]
I saw that extension have this feature, but when i use it first time I had not an option to select Scrum =(

**Comment by kglu** [comment]
I don't think that it was possible..
Any way, thank you for this extension!

**Comment by konradsikorski** [comment]
Hi. I have found time to work on this extension and you were right, there was hardcoded template name. It was fixed in the latest version of this extension. Thanks.
